//This class is generated by editor code
//we should have an editor utility which will generate constant fields of many types. For example a plain string vs folder path/ file path etc
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace com.rvkm.unitygames.gameplayFramework
{
    public static class ConstantManager
    {
        public const string tagAssetPathResourceFolder = "runtimeTags.asset";
        public const string runtimeTagAsset_RelativePath = "Assets/com.rvkm.unitygames.gameplayFramework/Tag/Resources/runtimeTags.asset";
    }
}